name: super-linter

on:
  push:
    branches:
      - main # Run when code is pushed to the main branch
  pull_request:
    branches:
      - main # Run on PRs targeting the main branch

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Run Super-Linter
      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          DEFAULT_BRANCH: main # Set the default branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to interact with the GitHub API
          VALIDATE_ALL_CODEBASE: true # Lint all files
          VALIDATE_JAVASCRIPT_ES: true # Enable JS linting
          VALIDATE_PYTHON: true        # Enable Python linting
          VALIDATE_YAML: true          # Enable YAML linting
          VALIDATE_MARKDOWN: true      # Enable Markdown linting
